### ISSUE TITLE
Commits have wrong author

### ISSUE THREAD

**Issue by espspinix** [LivelyKernel/lively4-core#48]
I have committed two times today, and both times my commit was created using a different author.
How is this possible?

https://github.com/LivelyKernel/active-expressions/commit/eb8613e25488e642014bcfdc9ad558d5c2235339

https://github.com/LivelyKernel/lively4-core/commit/d4342c196d5a4ff62ce5ff2a75257e6ccd09fcdf

An automatic sync after one of the commits was then created under my name:
https://github.com/LivelyKernel/active-expressions/commit/0807545d42b22ffa1d4b5bef4e1d41052894365c

**Comment by JensLincke** [comment]
I think, that I commited your changes... in the first commit. the content is not what the diff is about. ource sync scripts must have been run at the same time. Hmm, interesting

**Comment by espspinix** [comment]
Problem seems to persist, I just committed and synced more changes under your name:

https://github.com/LivelyKernel/lively4-core/commit/e560ec78f28032747bf9d10fecd0b602441a3720

**Comment by espspinix** [comment]
Seems like the problem is, that the github user and mail is not set (like in the sync shell script) before committing:
https://github.com/LivelyKernel/lively4-server/blob/master/httpServer.js#L292

**Comment by JensLincke** [comment]
fixed, can you try it out?

**Comment by Thulur** [comment]
@JensLincke the Problem remains.
In the "GitHub Sync" Tool the status button displays other people names when I'm commiting stuff.
![grafik](https://user-images.githubusercontent.com/7317880/32168036-4bf415e8-bd6b-11e7-9117-999ddad84198.png)

All commits concerning the service worker are made by me in this screenshot.
