### ISSUE TITLE
Cannot drag-select in Lively's address bar

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/lively4-core#78]
When I try to select part of the current URL with the mouse, it lets me drag the whole page like an image instead:

![2016-08-05_19-32-10](https://cloud.githubusercontent.com/assets/151175/17445127/a47270a6-5b43-11e6-8658-210900721e0c.gif)

Chrome 51.0.2704.79 m

**Comment by JensLincke** [comment]
This should have been fixed this morning already.

**Comment by j4yk** [comment]
Unfortunately, the issue persists even after emptying the cache and reloading the page.

**Comment by JensLincke** [comment]
the issue was fixed in the master... where did you test it?

**Comment by JensLincke** [comment]
(https://lively-kernel.org/lively4/lively4-core) was not synced yet, if you tried it there...
